name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Debug
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Build Release
      run: dotnet build --no-restore --configuration Release

    - name: Pack Pre-release Nuget Package
      run: nuget pack RD.Extensions.Enums.nuspec -OutputDirectory ./nupkg -Version 1.0.${{ github.run_number }}-prerelease

    - name: Pack Release Nuget Package
      run: nuget pack RD.Extensions.Enums.nuspec -OutputDirectory ./nupkg -Version 1.0.${{ github.run_number }}

    - name: Upload Artificats
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./nupkg/*.nupkg
