name: Nuget Prerelease

on:
  workflow_run:
      workflows: ["CI"]
      branches: [main]
      types:
        - completed

jobs:
  publish_package:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: nuget-packages

    - name: Publish Nuget Package
      run: dotnet nuget push ./nupkg/*-prerelease.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}