name: Prerelease

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release --version-suffix "pre${{ github.run_number }}"

    - name: Pack
      run: dotnet pack --no-build --configuration Release --output out --version-suffix "pre${{ github.run_number }}"

    - name: Push
      with:
        dotnet-version: 8.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./out/*.nupkg
